##------------------------------------------
##--- Author: Pradeep Singh
##--- Blog: https://iotbytes.wordpress.com/programmatically-send-e-mail-from-raspberry-pi-using-python-and-gmail/
##--- Date: 21st Feb 2017
##--- Version: 1.0
##--- Description: SMTP settings for email_handler.py
##------------------------------------------


[EMAIL]
; SMTP Server Address (For Gmail use smtp.gmail.com)
SMTP_ADD=smtp.ionos.com
; SMTP Server Port (Gmail default smtp port 465)
SMTP_PORT=587
; From email Address (For Gmail you may use you email id)
FROM_ADD=name@example.com
; SMTP Server User Name (for authentication)
USERNAME=name@example.com
; SMTP Server Password (for authentication)
PASSWORD=pw!!!!
